import Head from 'next/head';
import NavBar from '@/components/NavBar';
import Headline from '@/components/Headline';
import Footer from '@/components/Footer';
import PhotoSection from '@/components/PhotoSection';
import ProductPanel from '@/components/ProductPanel';
import About from '@/components/About';
import OurClients from '@/components/OurClients';
import OurWarehouse from '@/components/OurWarehouse';
import ContactMe from '@/components/ContactMe';

export default function Home() {
  return (
    <>
      <Head>
        <title>LEOM Sourcing</title>
        <meta name="description" content="Generated by IbanezCo" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>

        <div className='flex w-full'>
          <NavBar />
        </div>
        <Headline/>
        <PhotoSection />
        <ProductPanel/>
        <About/>
        <OurClients/>
        <OurWarehouse/>

        <div id='ContactMe'>
        <ContactMe />
        </div>

      </main>
      <Footer/>
    </>
  )
}
